name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # O la versión que necesites

      # Paso 3: Instalar dependencias
      - name: Install Dependencies
        run: npm ci

      # Paso 4: Ejecutar el build de Vite
      - name: Build
        run: npm run build

      # Paso 5: Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Opcional: si deseas configurar la rama de destino, por defecto es "gh-pages"
          # publish_branch: gh-pages
